stages:
  - deploy

deploy-to-staging:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -yq nodejs
    - apt-get install -yq npm
    - npm install
    - echo "Deploy to staging server"
    - curl -s "https://api.render.com/deploy/srv-$DEPLOY_HOOK_01?key=$DEPLOY_HOOK_02" -o file.txt >/dev/null 2>&1
  environment:
    name: staging
    url: https://dashboard.render.com/web/srv-$DEPLOY_HOOK_01
  only:
    - staging
