name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Deploy
        uses: bounceapp/render-action@0.6.0
        with:
          service-id: { { secrets.SERVICE_ID } }
          api-key: { { secrets.RENDER_API_KEY } }
