stages:
  - deploy

deploy-to-staging:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -yq nodejs
    - apt-get install -yq npm
    - npm install
    - npm install -g @bounce/render-action@0.6.0
    - render deploy --service-id=$SERVICE_ID --api-key=$RENDER_API_KEY
  environment:
    name: staging
  only:
    - staging
