
# Wrangler Configuration

# Resources:
# https://developers.cloudflare.com/workers/quickstart/
# https://developers.cloudflare.com/workers/tooling/wrangler/configuration/

name = "stikom-backend"
compatibility_date = "2025-06-09"

[build.upload]
format = "modules"
main = "./build/index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.staging]
name = "app-staging"

[env.production]
name = "app-production"