
# Wrangler Configuration

# Resources:
# https://developers.cloudflare.com/workers/quickstart/
# https://developers.cloudflare.com/workers/tooling/wrangler/configuration/

name = "stikom-backend"
compatibility_date = "2025-06-09"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

main = "./build/index.js"

[observability.logs]
enabled = true