
# Wrangler Configuration

# Resources:
# https://developers.cloudflare.com/workers/quickstart/
# https://developers.cloudflare.com/workers/tooling/wrangler/configuration/

name = "stikom-backend"
main = "build"

[env.staging]
name = "app-staging"

[env.production]
name = "app-production"