name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          environment: production
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            PORT
            ACCESS_TOKEN_SECRET
            DATABASE_HOST
            DATABASE_NAME
            DATABASE_PASSWORD
            DATABASE_PORT
            DATABASE_USERNAME
            REFRESH_TOKEN_SECRET
            SECRET_PORT
            STRAVA_CLIENT_ID
            STRAVA_CLIENT_SECRET
            DATABASE_URL
            CLOUDINARY_URL
            CLOUDINARY_API_NAME
            CLOUDINARY_API_KEY
            CLOUDINARY_API_SECRET
        env:
          PORT: ${{ secrets.PORT }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          SECRET_PORT: ${{ secrets.SECRET_PORT }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          CLOUDINARY_API_NAME: ${{ secrets.CLOUDINARY_API_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
